apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: warclusterstg/products:v1.0.1
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: SERVICE_NAME
              value: products
            - name: MONGODB_HOST
              value: mongo
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_DATABASE
              value: admin
            - name: MONGODB_USER
              value: root
            - name: MONGODB_PASSWORD
              value: example